import type { MetadataRoute } from "next";

import { siteConfig } from "@/lib/site-config";

/**
 * The PWA icons already exist (generated by `npm run brand`) and layout.tsx
 * declares them as favicons, but without a manifest nothing tells the browser
 * they are installable-app icons. Colours match the `themeColor` in layout.tsx.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${siteConfig.name} — ${siteConfig.tagline}`,
    short_name: siteConfig.name,
    description: siteConfig.description,
    start_url: "/",
    display: "standalone",
    background_color: "#050505",
    theme_color: "#050505",
    icons: [
      { src: "/brand/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/brand/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/brand/apple-icon-180.png", sizes: "180x180", type: "image/png" },
    ],
  };
}
